# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171227_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend_by',
        ),
    ]
