# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_friend_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishitem',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
