# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171228_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitem',
            name='wished_by',
        ),
        migrations.AddField(
            model_name='wishitem',
            name='wished_by',
            field=models.ManyToManyField(related_name='wishes', to='users.User'),
        ),
    ]
