# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-30 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171228_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('travel_from', models.DateField(default=0)),
                ('travel_end', models.DateField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wishitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wishitem',
            name='wished_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_hired',
        ),
        migrations.DeleteModel(
            name='wishitem',
        ),
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creates', to='users.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='joined_by',
            field=models.ManyToManyField(related_name='joins', to='users.User'),
        ),
    ]
